Kroy Have you ever heard of the "Rama"?
Creatures of unknown origin...
they say they appeared in the land of man before ancient times...
they possessed supernatural abilities that defies logic
with their abilities, they managed to turn inhabitable lands into prosperity and helped humanity build their lands around the world
and even after all that...
they only asked for one thing in return...
to stay hidden from humans forever so they can stay hidden and slumber in peace...
and ever since then, No human has ever laid their eyes on them for millenniums...
